-- ==============================================================================
-- STANOMER DATABASE MIGRATION - VERSION 2.0.3 AGENCY DIRECTORY & DETAILS
-- Date: 2026-08-19
-- Target: Supabase PostgreSQL (Idempotent & Safe for Live/Production Deployment)
-- Description:
--   1. Real Estate Agencies Master Table (`agencies`)
--   2. Agency Phone Contacts Child Table (`agency_phones`)
--   3. Agency Email Contacts Child Table (`agency_emails`)
--   4. Optimized Public Directory View/Table (`view_clean_agencies`) for the website
--      pages (/real-estate-agencies, /find-agency, /acente-bul).
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. AGENCIES MASTER TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    long_name TEXT DEFAULT NULL,
    city TEXT DEFAULT NULL,
    address TEXT DEFAULT NULL,
    website TEXT DEFAULT NULL,
    is_partner BOOLEAN DEFAULT FALSE,
    uses_stanomer BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS agencies_city_idx ON public.agencies (city);
CREATE INDEX IF NOT EXISTS agencies_name_idx ON public.agencies (name);

ALTER TABLE public.agencies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agencies_select_policy" ON public.agencies;
CREATE POLICY "agencies_select_policy" ON public.agencies
    FOR SELECT TO public USING (true);

-- ------------------------------------------------------------------------------
-- 2. AGENCY_PHONES CHILD TABLE (1:N Contact Phones)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agency_phones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT REFERENCES public.agencies(id) ON DELETE CASCADE,
    phone TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS agency_phones_agency_id_idx ON public.agency_phones (agency_id);

ALTER TABLE public.agency_phones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agency_phones_select_policy" ON public.agency_phones;
CREATE POLICY "agency_phones_select_policy" ON public.agency_phones
    FOR SELECT TO public USING (true);

-- ------------------------------------------------------------------------------
-- 3. AGENCY_EMAILS CHILD TABLE (1:N Contact Emails)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agency_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT REFERENCES public.agencies(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS agency_emails_agency_id_idx ON public.agency_emails (agency_id);

ALTER TABLE public.agency_emails ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agency_emails_select_policy" ON public.agency_emails;
CREATE POLICY "agency_emails_select_policy" ON public.agency_emails
    FOR SELECT TO public USING (true);

-- ------------------------------------------------------------------------------
-- 4. VIEW_CLEAN_AGENCIES TABLE & SEARCH INDEXES (Website Fast Directory)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.view_clean_agencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acente_adi TEXT NOT NULL,
    resmi_tam_unvan TEXT DEFAULT NULL,
    sehir TEXT DEFAULT NULL,
    adres TEXT DEFAULT NULL,
    web_sitesi TEXT DEFAULT NULL,
    telefonlar TEXT DEFAULT NULL,
    eposta_adresleri TEXT DEFAULT NULL,
    is_partner BOOLEAN DEFAULT FALSE,
    uses_stanomer BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Search and filtering indexes
CREATE INDEX IF NOT EXISTS view_clean_agencies_sehir_idx ON public.view_clean_agencies (sehir);
CREATE INDEX IF NOT EXISTS view_clean_agencies_acente_adi_idx ON public.view_clean_agencies (acente_adi);
CREATE INDEX IF NOT EXISTS view_clean_agencies_partner_idx ON public.view_clean_agencies (is_partner);
CREATE INDEX IF NOT EXISTS view_clean_agencies_uses_stanomer_idx ON public.view_clean_agencies (uses_stanomer);

ALTER TABLE public.view_clean_agencies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "view_clean_agencies_select_policy" ON public.view_clean_agencies;
CREATE POLICY "view_clean_agencies_select_policy" ON public.view_clean_agencies
    FOR SELECT TO public USING (true);

-- ==============================================================================
-- END OF VERSION 2.0.3 MIGRATION SCRIPT
-- ==============================================================================
