const translations = {
    "tr": {
        "nav_features": "Özellikler",
        "nav_roles": "Roller",
        "nav_app": "Uygulamaya Git",
        "hero_badge": "PropTech'te Yeni Standart",
        "hero_title": "Mülk Yönetiminde Yeni Nesil Dönem.",
        "hero_desc": "Ev sahipleri ve kiracılar arasındaki şeffaflık boşluğunu Stanomer ile doldurun. Kontratlar, ödemeler ve arıza takibi artık tek bir noktada.",
        "hero_cta_free": "Ücretsiz Başlayın",
        "hero_cta_explore": "Keşfedin",
        "hero_card_paid": "Kira Ödendi",
        "hero_card_issue": "Yeni Arıza Bildirimi",
        "roles_title": "Her İki Taraf İçin de Kazan-Kazan",
        "roles_desc": "Stanomer, hem mülk sahiplerinin hem de kiracıların beklentilerini tek bir platformda karşılar.",
        "landlord_title": "Ev Sahipleri İçin",
        "landlord_f1": "Otomatik kira takibi ve gecikme uyarıları.",
        "landlord_f2": "Dijital kontrat müzakeresi ve arşivi.",
        "landlord_f3": "Arıza ve bakım süreçlerinin merkezi yönetimi.",
        "tenant_title": "Kiracılar İçin",
        "tenant_f1": "Tek tıkla arıza bildirimi ve durum takibi.",
        "tenant_f2": "Güvenli makbuz yükleme ve ödeme onayı.",
        "tenant_f3": "Tüm belgelere 7/24 mobil erişim.",
        "feature_shield": "Dijital Güven",
        "feature_shield_desc": "Kontrat değişiklikleri ve ödemeler her iki tarafın onayıyla onaylanır.",
        "feature_lang": "Çoklu Dil Desteği",
        "feature_lang_desc": "TR, EN ve SR dilleriyle uluslararası mülk yönetimi artık çok daha kolay.",
        "feature_zap": "Anlık Bildirimler",
        "feature_zap_desc": "Hiçbir detayı kaçırmayın. Ödemeler ve bakım süreçleri cebinizde.",
        "footer_rights": "Tüm hakları saklıdır.",
        "footer_privacy": "Gizlilik Politikası",
        "footer_terms": "Kullanım Şartları"
    },
    "en": {
        "nav_features": "Features",
        "nav_roles": "Roles",
        "nav_app": "Go to App",
        "hero_badge": "Next Standard in PropTech",
        "hero_title": "A New Era in Property Management.",
        "hero_desc": "Bridge the transparency gap between landlords and tenants with Stanomer. Contracts, payments, and maintenance, all in one place.",
        "hero_cta_free": "Get Started Free",
        "hero_cta_explore": "Explore",
        "hero_card_paid": "Rent Paid",
        "hero_card_issue": "New Maintenance Request",
        "roles_title": "Win-Win for Everyone",
        "roles_desc": "Stanomer meets the expectations of both property owners and tenants on a single platform.",
        "landlord_title": "For Landlords",
        "landlord_f1": "Automated rent tracking and overdue alerts.",
        "landlord_f2": "Digital contract negotiation and archive.",
        "landlord_f3": "Centralized maintenance management.",
        "tenant_title": "For Tenants",
        "tenant_f1": "One-tap issue reporting and tracking.",
        "tenant_f2": "Secure receipt upload and payment approval.",
        "tenant_f3": "24/7 mobile access to all documents.",
        "feature_shield": "Digital Trust",
        "feature_shield_desc": "Contract changes and payments are confirmed by both parties.",
        "feature_lang": "Multi-Language Support",
        "feature_lang_desc": "International management made easy with TR, EN, and SR support.",
        "feature_zap": "Instant Notifications",
        "feature_zap_desc": "Never miss a detail. Payments and maintenance in your pocket.",
        "footer_rights": "All rights reserved.",
        "footer_privacy": "Privacy Policy",
        "footer_terms": "Terms of Use"
    },
    "sr": {
        "nav_features": "Funkcije",
        "nav_roles": "Uloge",
        "nav_app": "Idi na aplikaciju",
        "hero_badge": "Novi standard u PropTech-u",
        "hero_title": "Nova era upravljanja nekretninama.",
        "hero_desc": "Popunite jaz u transparentnosti između stanodavaca i stanara uz Stanomer. Ugovori, plaćanja i održavanje, sve na jednom mestu.",
        "hero_cta_free": "Započni besplatno",
        "hero_cta_explore": "Istraži",
        "hero_card_paid": "Kirija plaćena",
        "hero_card_issue": "Novi zahtev za održavanje",
        "roles_title": "Dobitna kombinacija za obe strane",
        "roles_desc": "Stanomer ispunjava očekivanja i vlasnika nekretnina i stanara na jednoj platformi.",
        "landlord_title": "Za stanodavce",
        "landlord_f1": "Automatsko praćenje kirije i upozorenja o kašnjenju.",
        "landlord_f2": "Digitalni pregovori o ugovoru i arhiva.",
        "landlord_f3": "Centralizovano upravljanje održavanjem.",
        "tenant_title": "Za stanare",
        "tenant_f1": "Prijava kvara i praćenje statusa jednim klikom.",
        "tenant_f2": "Bezbedno otpremanje priznanica i potvrda plaćanja.",
        "tenant_f3": "24/7 mobilni pristup svim dokumentima.",
        "feature_shield": "Digitalno poverenje",
        "feature_shield_desc": "Promene ugovora i plaćanja potvrđuju obe strane.",
        "feature_lang": "Višejezična podrška",
        "feature_lang_desc": "Međunarodno upravljanje olakšano uz TR, EN i SR podršku.",
        "feature_zap": "Instant obaveštenja",
        "feature_zap_desc": "Nikada ne propustite detalj. Plaćanja i održavanje u vašem džepu.",
        "footer_rights": "Sva prava zadržana.",
        "footer_privacy": "Politika privatnosti",
        "footer_terms": "Uslovi korišćenja"
    },
    "sr_Cyrl": {
        "nav_features": "Функције",
        "nav_roles": "Улоге",
        "nav_app": "Иди на апликацију",
        "hero_badge": "Нови стандард у PropTech-у",
        "hero_title": "Нова ера управљања некретнинама.",
        "hero_desc": "Попуните јаз у транспарентности између станодаваца и станара уз Станомер. Уговори, плаћања и одржавање, све на једном месту.",
        "hero_cta_free": "Започни бесплатно",
        "hero_cta_explore": "Истражи",
        "hero_card_paid": "Кирија плаћена",
        "hero_card_issue": "Нови захтев за одржавање",
        "roles_title": "Добитна комбинација за обе стране",
        "roles_desc": "Станомер испуњава очекивања и власника некретнина и станара на једној платформи.",
        "landlord_title": "За станодавце",
        "landlord_f1": "Аутоматско праћење кирије и упозорења о кашњењу.",
        "landlord_f2": "Дигитални преговори о уговору и архива.",
        "landlord_f3": "Централизовано управљање одржавањем.",
        "tenant_title": "За станаре",
        "tenant_f1": "Пријава квара и праћење статуса једним кликом.",
        "tenant_f2": "Безбедно отпремање признаница и потврда плаћања.",
        "tenant_f3": "24/7 мобилни приступ свим документима.",
        "feature_shield": "Дигитално поверење",
        "feature_shield_desc": "Промене уговора и плаћања потврђују обе стране.",
        "feature_lang": "Вишејезична подршка",
        "feature_lang_desc": "Међународно управљање олакшано уз ТР, ЕН и СР подршку.",
        "feature_zap": "Инстант обавештења",
        "feature_zap_desc": "Никада не пропустите детаљ. Плаћања и одржавање у вашем џепу.",
        "footer_rights": "Сва права задржана.",
        "footer_privacy": "Политика приватности",
        "footer_terms": "Услови коришћења"
    }
};

window.translations = translations;
