const translations = {
    "tr": {
        "nav_app": "Web App",
        "hero_badge": "Dijital Kira Defteri",
        "hero_title": "Artık Kağıt Kalem<br>Arasındaki Kira Notlarına <span>Son!</span>",
        "hero_desc": "WhatsApp'ta dekont aramakla, not kağıtlarına bakmakla uğraşmayın. Stanomer tüm kira takibinizi sizin yerinize yapar — kullanımı çok basit.",
        "hero_note": "Tek mülkünüz varsa tamamen ücretsiz. Kredi kartı gerekmez.",
        "pain_strip": "<strong>Tanıdık geliyor mu?</strong> Kiracı kirayı yatırdı mı yatırmadı mı bilmiyorsunuz. Kira sözleşmesini bulmak için çantanızı karıştırıyorsunuz. Musluğun bozulduğunu WhatsApp'ta 3 günlük mesajlar arasından öğrendiniz. — <strong>Stanomer tam bu karışıklığı bitirir.</strong>",
        "roles_label": "Herkes için hazır",
        "roles_landlord": "Ev Sahipleri İçin",
        "roles_landlord_1": "Kira günü geçtiğinde size haber gelir",
        "roles_landlord_2": "Sözleşmeyi bir kez yükleyin, her an elinizin altında",
        "roles_landlord_3": "Hangi kiracı ne kadar ödedi, hepsi tek ekranda",
        "roles_landlord_4": "Ev arızalarını oradan takip edin",
        "roles_tenant": "Kiracılar İçin",
        "roles_tenant_1": "Ödediğinizin makbuzunu hemen gönderin",
        "roles_tenant_2": "Musluk bozuldu? Bir tıkla bildirin",
        "roles_tenant_3": "Sözleşmenize 7/24 telefonda bakın",
        "roles_tenant_4": "Her şey kayıt altında, ihtilaf yok",
        "steps_title": "3 Adımda Başlayın",
        "step_1_title": "Dairenizi tanımlayın",
        "step_1_desc": "Evinizin adresini ve kira miktarını bir kez yazın. Beş dakika bile sürmez.",
        "step_2_title": "Kiracınızı davet edin",
        "step_2_desc": "Kiracınızın telefonuna bir bağlantı gönderin, o da uygulamaya dahil olsun.",
        "step_3_title": "Keyfinize bakın",
        "step_3_desc": "Kira ödendiğinde tek dokunuşla onaylayın. Gerisini Stanomer halleder.",
        "trust_label": "Güvenlik ve kolaylık",
        "trust_1_title": "Bilgileriniz güvende",
        "trust_1_desc": "İzniniz olmadan kimse verilerinizi göremez",
        "trust_2_title": "Telefon bozulsa da kaybolmaz",
        "trust_2_desc": "Her şey güvenli sunucuda saklanır",
        "trust_3_title": "Yardım yanınızda",
        "trust_3_desc": "Takıldığınız yerde biz hep buradayız",
        "features_label": "Neler yapabilirsiniz",
        "feature_1_title": "Dijital kira defteri",
        "feature_1_desc": "Kim ne zaman ne kadar ödedi — tıpkı bir defter gibi alt alta sıralanmış. Artık kafanızda hesap tutmak yok.",
        "feature_2_title": "Sözleşme kasası",
        "feature_2_desc": "Sözleşmenizin fotoğrafını bir kez çekip yükleyin. Gerektiğinde saniyeler içinde bulun, kağıt yığını aramayın.",
        "feature_3_title": "Otomatik hatırlatmalar",
        "feature_3_desc": "Kira günü yaklaşınca hem siz hem kiracınız uyarılırsınız. Ödeme gelince anında bildirim alırsınız.",
        "feature_4_title": "Arıza takibi",
        "feature_4_desc": "Kiracınız evde bir sorun olduğunda size uygulama üzerinden bildirir. Mesajlar arasında kaybolmaz, her şey kayıt altında.",
        "feature_5_title": "Türkçe, İngilizce, Sırpça",
        "feature_5_desc": "Yabancı uyruklu kiracınız mı var? Uygulama onun diliyle de çalışır.",
        "footer_cta_title": "Bugün Başlayın, Fark Hissedin",
        "footer_cta_desc": "Tek mülkünüz varsa tamamen ücretsiz. Kurulum yok, karmaşık ayar yok.<br>WhatsApp'ı kullanabiliyorsanız Stanomer'i de kullanabilirsiniz.",
        "btn_web_app": "Web Uygulamasına Git →",
        "footer_rights": "Tüm hakları saklıdır.",
        "footer_privacy": "Gizlilik Politikası",
        "footer_terms": "Kullanım Şartları"
    },
    "en": {
        "nav_app": "Web App",
        "hero_badge": "Digital Rent Ledger",
        "hero_title": "Say Goodbye to Rent Notes<br>on Paper and Pen!",
        "hero_desc": "Stop searching for receipts in WhatsApp or looking at sticky notes. Stanomer handles all rent tracking for you — it's very simple to use.",
        "hero_note": "Completely free if you have one property. No credit card required.",
        "pain_strip": "<strong>Sound familiar?</strong> You don't know if the tenant paid the rent. You're digging through your bag to find the lease agreement. You found out the faucet was broken from 3-day-old WhatsApp messages. — <strong>Stanomer ends this chaos.</strong>",
        "roles_label": "Ready for everyone",
        "roles_landlord": "For Landlords",
        "roles_landlord_1": "Get notified when rent is overdue",
        "roles_landlord_2": "Upload the contract once, keep it handy anytime",
        "roles_landlord_3": "See who paid how much, all on one screen",
        "roles_landlord_4": "Track property maintenance issues easily",
        "roles_tenant": "For Tenants",
        "roles_tenant_1": "Send your payment receipt instantly",
        "roles_tenant_2": "Faucet broken? Report with one click",
        "roles_tenant_3": "View your contract 24/7 on your phone",
        "roles_tenant_4": "Everything is recorded, no disputes",
        "steps_title": "Get Started in 3 Steps",
        "step_1_title": "Define your property",
        "step_1_desc": "Enter your property address and rent amount once. Takes less than five minutes.",
        "step_2_title": "Invite your tenant",
        "step_2_desc": "Send a link to your tenant's phone, and they'll join the app.",
        "step_3_title": "Enjoy peace of mind",
        "step_3_desc": "Approve with one tap when rent is paid. Stanomer handles the rest.",
        "trust_label": "Security and convenience",
        "trust_1_title": "Your data is safe",
        "trust_1_desc": "No one can see your data without your permission",
        "trust_2_title": "Safe even if phone breaks",
        "trust_2_desc": "Everything is stored on secure servers",
        "trust_3_title": "Help is nearby",
        "trust_3_desc": "We are always here when you get stuck",
        "features_label": "What you can do",
        "feature_1_title": "Digital rent ledger",
        "feature_1_desc": "Who paid how much and when — listed like a ledger. No more mental math.",
        "feature_2_title": "Contract vault",
        "feature_2_desc": "Take a photo of your contract and upload it once. Find it in seconds when needed.",
        "feature_3_title": "Automated reminders",
        "feature_3_desc": "You and your tenant are alerted when rent day approaches. Instant notifications on payment.",
        "feature_4_title": "Maintenance tracking",
        "feature_4_desc": "Your tenant notifies you via the app when there's an issue. Nothing gets lost in messages.",
        "feature_5_title": "English, Turkish, Serbian",
        "feature_5_desc": "Have a foreign tenant? The app works in their language too.",
        "footer_cta_title": "Start Today, Feel the Difference",
        "footer_cta_desc": "Completely free if you have one property. No setup, no complex settings.<br>If you can use WhatsApp, you can use Stanomer.",
        "btn_web_app": "Go to Web App →",
        "footer_rights": "All rights reserved.",
        "footer_privacy": "Privacy Policy",
        "footer_terms": "Terms of Use"
    },
    "sr": {
        "nav_app": "Web App",
        "hero_badge": "Digitalna knjiga kirija",
        "hero_title": "Recite zbogom beleškama o kiriji<br>na papiru!",
        "hero_desc": "Prestanite da tražite priznanice na Viber-u ili beleškama. Stanomer preuzima celokupno praćenje kirije — veoma je jednostavan za korišćenje.",
        "hero_note": "Potpuno besplatno za jednu nekretninu. Nije potrebna kreditna kartica.",
        "pain_strip": "<strong>Zvuči poznato?</strong> Ne znate da li je stanar platio kiriju. Tražite ugovor o zakupu po torbama. Saznali ste da je slavina pokvarena iz Viber poruke od pre 3 dana. — <strong>Stanomer rešava ovaj haos.</strong>",
        "roles_label": "Spreman za svakoga",
        "roles_landlord": "Za Stanodavce",
        "roles_landlord_1": "Dobijte obaveštenje kada kirija kasni",
        "roles_landlord_2": "Otpremite ugovor jednom, uvek pri ruci",
        "roles_landlord_3": "Vidite ko je koliko platio, sve na jednom ekranu",
        "roles_landlord_4": "Lako pratite probleme sa održavanjem",
        "roles_tenant": "Za Stanare",
        "roles_tenant_1": "Pošaljite potvrdu o plaćanju odmah",
        "roles_tenant_2": "Pokvarena slavina? Prijavite jednim klikom",
        "roles_tenant_3": "Pogledajte ugovor 24/7 na telefonu",
        "roles_tenant_4": "Sve je zabeleženo, nema sporova",
        "steps_title": "Započnite u 3 koraka",
        "step_1_title": "Definišite svoju nekretninu",
        "step_1_desc": "Unesite adresu i iznos kirije jednom. Traje manje od pet minuta.",
        "step_2_title": "Pozovite svog stanara",
        "step_2_desc": "Pošaljite link na telefon stanara, i on će se pridružiti aplikaciji.",
        "step_3_title": "Uživajte u miru",
        "step_3_desc": "Odobrite jednim dodirom kada je kirija plaćena. Stanomer brine o ostalom.",
        "trust_label": "Sigurnost i udobnost",
        "trust_1_title": "Vaši podaci su sigurni",
        "trust_1_desc": "Niko ne može videti vaše podatke bez dozvole",
        "trust_2_title": "Sigurno čak i ako se telefon pokvari",
        "trust_2_desc": "Sve je sačuvano na sigurnim serverima",
        "trust_3_title": "Pomoć je blizu",
        "trust_3_desc": "Uvek smo tu kada vam zatreba pomoć",
        "features_label": "Šta možete da uradite",
        "feature_1_title": "Digitalna knjiga kirija",
        "feature_1_desc": "Ko je platio, koliko i kada — poređano kao u knjizi. Nema više računanja napamet.",
        "feature_2_title": "Trezor za ugovore",
        "feature_2_desc": "Slikajte ugovor i otpremite ga jednom. Pronađite ga u sekundi kada je potrebno.",
        "feature_3_title": "Automatski podsetnici",
        "feature_3_desc": "Vi i vaš stanar ste upozoreni kada se bliži dan kirije. Instant obaveštenja o uplati.",
        "feature_4_title": "Praćenje održavanja",
        "feature_4_desc": "Stanar vas obaveštava putem aplikacije kada postoji problem. Ništa se ne gubi u porukama.",
        "feature_5_title": "Srpski, Engleski, Turski",
        "feature_5_desc": "Imate stranog stanara? Aplikacija radi i na njegovom jeziku.",
        "footer_cta_title": "Započnite danas, osetite razliku",
        "footer_cta_desc": "Potpuno besplatno za jednu nekretninu. Nema komplikovanih podešavanja.<br>Ako znate da koristite Viber, znaćete i Stanomer.",
        "btn_web_app": "Idi na Web Aplikaciju →",
        "footer_rights": "Sva prava zadržana.",
        "footer_privacy": "Politika privatnosti",
        "footer_terms": "Uslovi korišćenja"
    },
    "sr_Cyrl": {
        "nav_app": "Web App",
        "hero_badge": "Дигитална књига кирија",
        "hero_title": "Реците збогом белешкама о кирији<br>на папиру!",
        "hero_desc": "Престаните да тражите признанице на Viber-у или белешкама. Станомер преузима целокупно праћење кирије — веома је једноставан за коришћење.",
        "hero_note": "Потпуно бесплатно за једну некретнину. Није потребна кредитна картица.",
        "pain_strip": "<strong>Звучи познато?</strong> Не знате да ли је станар платио кирију. Тражите уговор о закупу по торбама. Сазнали сте да је славина покварена из Viber поруке од пре 3 дана. — <strong>Станомер решава овај хаос.</strong>",
        "roles_label": "Спреман за свакога",
        "roles_landlord": "За Станодавце",
        "roles_landlord_1": "Добијте обавештење када кирија касни",
        "roles_landlord_2": "Отпремите уговор једном, увек при руци",
        "roles_landlord_3": "Видите ко је колико платио, све на једном екрану",
        "roles_landlord_4": "Лако пратите проблеме са одржавањем",
        "roles_tenant": "За Станаре",
        "roles_tenant_1": "Пошаљите потврду о плаћању одмах",
        "roles_tenant_2": "Покварена славина? Пријавите једним кликом",
        "roles_tenant_3": "Погледајте уговор 24/7 на телефону",
        "roles_tenant_4": "Све је забележено, нема спорова",
        "steps_title": "Започните у 3 корака",
        "step_1_title": "Дефинишите своју некретнину",
        "step_1_desc": "Унесите адресу и износ кирије једном. Траје мање од пет минута.",
        "step_2_title": "Позовите свог станара",
        "step_2_desc": "Пошаљите линк на телефон станара, и он ће се придружити апликацији.",
        "step_3_title": "Уживајте у миру",
        "step_3_desc": "Одобрите једним додиром када је кирија плаћена. Станомер брине о осталом.",
        "trust_label": "Сигурност и удобност",
        "trust_1_title": "Ваши подаци су сигурни",
        "trust_1_desc": "Нико не може видети ваше податке без дозволе",
        "trust_2_title": "Сигурно чак и ако се телефон поквари",
        "trust_2_desc": "Све је сачувано на сигурним серверима",
        "trust_3_title": "Помоћ је близу",
        "trust_3_desc": "Увек смо ту када вам затреба помоћ",
        "features_label": "Шта можете да урадите",
        "feature_1_title": "Дигитална књига кирија",
        "feature_1_desc": "Ко је платио, колико и када — поређано као у књизи. Нема више рачунања напамет.",
        "feature_2_title": "Трезор за уговоре",
        "feature_2_desc": "Сликајте уговор и отпремите га једном. Пронађите га у секунди када је потребно.",
        "feature_3_title": "Аутоматски подсетници",
        "feature_3_desc": "Ви и ваш станар сте упозорени када се ближи дан кирије. Инстант обавештења о уплати.",
        "feature_4_title": "Праћење одржавања",
        "feature_4_desc": "Станар вас обавештава путем апликације када постоји проблем. Ништа се не губи у порукама.",
        "feature_5_title": "Српски, Енглески, Турски",
        "feature_5_desc": "Имате страног станара? Апликација ради и на његовом језику.",
        "footer_cta_title": "Започните данас, осетите разлику",
        "footer_cta_desc": "Потпуно бесплатно за једну некретнину. Нема компликованих подешавања.<br>Ако знате да користите Viber, знаћете и Станомер.",
        "btn_web_app": "Иди на Web Апликацију →",
        "footer_rights": "Сва права задржана.",
        "footer_privacy": "Политика приватности",
        "footer_terms": "Услови коришћења"
    },
    "ru": {
        "nav_app": "Веб-приложение",
        "hero_badge": "Цифровая книга аренды",
        "hero_title": "Попрощайтесь с записями<br>об аренде на <span>бумаге!</span>",
        "hero_desc": "Перестаньте искать квитанции в Viber или на бумажках. Stanomer берет на себя весь учет аренды — это очень просто в использовании.",
        "hero_note": "Абсолютно бесплатно для одной недвижимости. Кредитная карта не требуется.",
        "pain_strip": "<strong>Знакомая ситуация?</strong> Вы не знаете, заплатил ли арендатор. Ищете договор аренды по всем сумкам. Узнали о сломанном кране из сообщений в Viber 3-дневной давности. — <strong>Stanomer положит конец этому хаосу.</strong>",
        "roles_label": "Готово для всех",
        "roles_landlord": "Для Арендодателей",
        "roles_landlord_1": "Получайте уведомления о просрочке аренды",
        "roles_landlord_2": "Загрузите договор один раз, он всегда под рукой",
        "roles_landlord_3": "Смотрите, кто сколько заплатил, на одном экране",
        "roles_landlord_4": "Легко отслеживайте проблемы с обслуживанием",
        "roles_tenant": "Для Арендаторов",
        "roles_tenant_1": "Мгновенно отправляйте квитанцию об оплате",
        "roles_tenant_2": "Сломался кран? Сообщите в один клик",
        "roles_tenant_3": "Смотрите свой договор 24/7 на телефоне",
        "roles_tenant_4": "Все записано, никаких споров",
        "steps_title": "Начните за 3 шага",
        "step_1_title": "Добавьте недвижимость",
        "step_1_desc": "Введите адрес и сумму аренды один раз. Это займет меньше пяти минут.",
        "step_2_title": "Пригласите арендатора",
        "step_2_desc": "Отправьте ссылку на телефон арендатора, и он присоединится к приложению.",
        "step_3_title": "Наслаждайтесь спокойствием",
        "step_3_desc": "Подтверждайте оплату аренды одним касанием. Остальное сделает Stanomer.",
        "trust_label": "Безопасность и удобство",
        "trust_1_title": "Ваши данные в безопасности",
        "trust_1_desc": "Никто не увидит ваши данные без вашего разрешения",
        "trust_2_title": "Безопасно, даже если телефон сломается",
        "trust_2_desc": "Все хранится на защищенных серверах",
        "trust_3_title": "Помощь рядом",
        "trust_3_desc": "Мы всегда здесь, когда вам нужна помощь",
        "features_label": "Что вы можете сделать",
        "feature_1_title": "Цифровая книга аренды",
        "feature_1_desc": "Кто, сколько и когда заплатил — как в книге. Больше никаких подсчетов в уме.",
        "feature_2_title": "Хранилище договоров",
        "feature_2_desc": "Сфотографируйте договор и загрузите один раз. Находите за секунды при необходимости.",
        "feature_3_title": "Автоматические напоминания",
        "feature_3_desc": "Вы и ваш арендатор получаете предупреждения о приближении дня оплаты. Мгновенные уведомления об оплате.",
        "feature_4_title": "Отслеживание обслуживания",
        "feature_4_desc": "Арендатор уведомляет вас через приложение о проблеме. Ничего не теряется в сообщениях.",
        "feature_5_title": "Английский, Турецкий, Сербский, Русский",
        "feature_5_desc": "У вас иностранный арендатор? Приложение работает и на его языке.",
        "footer_cta_title": "Начните сегодня, почувствуйте разницу",
        "footer_cta_desc": "Абсолютно бесплатно для одной недвижимости. Никаких сложных настроек.<br>Если вы умеете пользоваться Viber, вы сможете пользоваться и Stanomer.",
        "btn_web_app": "Перейти в Веб-приложение →",
        "footer_rights": "Все права защищены.",
        "footer_privacy": "Политика конфиденциальности",
        "footer_terms": "Условия использования"
    }
};

window.translations = translations;
